### ISSUE TITLE
Consul 1.0.1 breaks reading the configmap config

### ISSUE THREAD

**Issue by vk-mattc** [kelseyhightower/consul-on-kubernetes#23] opened 2017-11-21 17:14 UTC
When running consul 1.0.1 I get the following error attempting to spin up consul using the artifacts in this tutorial

```
Percival-Derpington:manifests mattcase$ kubectl logs consul-0
==> config: ReadFile failed on /consul/config/..data: read /consul/config/..data: is a directory
```

Using the exact same configmap but utilizing 1.0.0 results in proper startup:

```
Percival-Derpington:manifests mattcase$ kubectl logs consul-0
==> Starting Consul agent...
bootstrap_expect > 0: expecting 3 servers
==> Consul agent running!
           Version: 'v1.0.0'
           Node ID: '4a369f12-a478-529f-c426-07db9baa7ac0'
         Node name: 'consul-0'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: 8443, DNS: 8600)
      Cluster Addr: 100.111.100.48 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: true
```

**Comment by vk-mattc** [comment] 2017-11-21 17:21
it's odd because it's configured via `-config-file=/consul/config/server.json` in the manifest for the StatefulSet, and `..data` is in fact a directory pointing to the mounted configmap. When investigating in the running 1.0.0 container I see the following:

```
/consul/config # ls -lha
total 12
drwxrwsrwx    3 consul   consul      4.0K Nov 21 17:03 .
drwxr-xr-x    4 consul   consul      4.0K Oct 31 18:24 ..
drwxr-sr-x    2 root     consul      4.0K Nov 21 17:03 ..119811_21_11_17_03_00.120617316
lrwxrwxrwx    1 root     root          33 Nov 21 17:03 ..data -> ..119811_21_11_17_03_00.120617316
lrwxrwxrwx    1 root     root          18 Nov 21 17:03 server.json -> ..data/server.json
```

So I'm not sure why it's trying to read `..data` as a file when it's being directed specifically to read `server.json`

**Comment by alpe** [comment] 2017-12-20 13:09
I have the same problem for `v1.0.2`

**Comment by fastest963** [comment] 2018-01-12 21:05
If you add consul as the first arg in the container then it bypasses the _unhelpful_ auto configuration that the entrypoint script tries to do. In particular, it automatically adds `-config-dir /consul/config`  which is what is breaking this.

```
           args:
+            - "consul"
             - "agent"
             - "-advertise=$(POD_IP)"
```

**Comment by wheelerlaw** [comment] 2018-01-16 01:04
I can also confirm that @fastest963's fix worked.

**Comment by vk-mattc** [comment] 2018-01-16 15:26
@fastest963 thanks for the update. I'm not able to check right this second if that fix also works in 1.0 and prior? I'll submit a PR to update the documentation based on your findings.

**Comment by fastest963** [comment] 2018-01-16 17:16
@vk-mattc I was mostly just putting a stopgap in here because there were some 1.0.1 fixes that we needed. I opened a PR against consul: https://github.com/hashicorp/consul/pull/3799 that will fix the issue (confirmed running that commit on master in our cluster). The fact that the docker entrypoint tries to be "helpful" and add `/consul/config/` could also be seen as the bug as well, since that folder contains symlinks (that consul doesn't support until 3799).

**Comment by fastest963** [comment] 2018-01-18 19:33
They just merged my PR against consul so we theoretically don't need to do that workaround I posted. This issue should also probably be closed.

**Comment by nik786** [comment] 2018-05-24 08:38
@fastest963 

Im using this config to deploy consul on kubernetes.

cat deployments/consul-1.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul-1
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
        member: consul-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "consul:1.0.1"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "consul"
            - "agent"
            - "-advertise=10.254.174.65"
            - "-rejoin"
            - "-bind=0.0.0.0"
            - "-ui"
            - "-node=consul-1"
            - "-server"
            - "-bootstrap-expect=3"
            - "-raft-protocol=3"
            - "-retry-join=kubernetes.default.svc.cluster.local"
            - "-retry-join=kubernetes.default.svc.cluster.local"
            - "-retry-join=kubernetes.default.svc.cluster.local"
            - "-client=0.0.0.0"
            - "-data-dir=/consul/data/"
            - "-domain=cluster.local" 
            - "-disable-host-node-id"
          ports:
            - containerPort: 8300
              name: server
            - containerPort: 8301
              name: serflan-tcp
              protocol: "TCP"
            - containerPort: 8301
              name: serflan-udp
              protocol: "UDP"
            - containerPort: 8302
              name: serfwan-tcp
              protocol: "TCP"
            - containerPort: 8302
              name: serfwan-udp
              protocol: "UDP"
            - containerPort: 8400
              name: rpc-port
            - containerPort: 8500
              name: api-port
            - containerPort: 8600
              name: consuldns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: consuldns-udp
              protocol: "UDP"
          volumeMounts:
            - name: "consulconfig"
              mountPath: /etc/consul
      volumes:
        - name: "consulconfig"
          "secret": {
            "secretName": "consul-config"
          }

but im facing issue

HTTP error code from Consul: 500 Internal Server Error

Error message from Consul: No cluster leader

Consul returned an error. You may have visited a URL that is loading an unknown resource, so you can try going back to the root. If your ACL token was not found you can reset it, and then you will be redirected to the settings page to enter a new ACL token.


    2018/05/24 08:35:29 [ERR] agent: failed to sync remote state: No cluster leader
    2018/05/24 08:35:33 [ERR] agent: Coordinate update error: No cluster leader
    2018/05/24 08:35:37 [INFO] agent: (LAN) joined: 0 Err: 3 error(s) occurred:

* Failed to join 10.254.0.1: dial tcp 10.254.0.1:8301: i/o timeout
* Failed to join 10.254.0.1: dial tcp 10.254.0.1:8301: i/o timeout
* Failed to join 10.254.0.1: dial tcp 10.254.0.1:8301: i/o timeout
    2018/05/24 08:35:37 [WARN] agent: Join LAN failed: <nil>, retrying in 30s
    2018/05/24 08:36:01 [ERR] agent: failed to sync remote state: No cluster leader
    2018/05/24 08:36:05 [ERR] agent: Coordinate update error: No cluster leader
    2018/05/24 08:36:07 [INFO] agent: (LAN) joining: [kubernetes.default.svc.cluster.local kubernetes.default.svc.cluster.local kubernetes.default.svc.cluster.local]
    2018/05/24 08:36:18 [ERR] http: Request GET /v1/coordinate/nodes?dc=dc1&token=<hidden>, error: No cluster leader from=172.17.8.1:37920
    2018/05/24 08:36:23 [ERR] agent: failed to sync remote state: No cluster leader
    2018/05/24 08:36:37 [INFO] agent: (LAN) joined: 0 Err: 3 error(s) occurred:

* Failed to join 10.254.0.1: dial tcp 10.254.0.1:8301: i/o timeout
* Failed to join 10.254.0.1: dial tcp 10.254.0.1:8301: i/o timeout

**Comment by israelshirk** [comment] 2018-07-06 04:00
Against 1.2.0 you get a similar issue regarding the docker entrypoint attempting to chmod /consul/config and failing due to it being a read-only FS.  #34 resolves this.

**Comment by kelseyhightower** [comment] 2018-11-04 00:44
I'm now using a different directory. This should be now fixed on master.

**Closed by kelseyhightower** 2018-11-04 00:44 UTC
